"""Auto-generated by refactor_split.py — DO NOT edit blindly.

Imports shared singletons (app, api_router, db) and helpers from `core`
to avoid circular dependencies. All `@api_router.*` decorators here
register routes on the same shared router that `server.py` mounts.
"""

import os
import uuid
import json
import requests
from datetime import datetime, timezone, timedelta
from typing import List, Optional

from fastapi import (
    HTTPException, Request, Response, UploadFile, File, Form, Header, Query,
)
from fastapi.responses import Response as FastAPIResponse
from pydantic import BaseModel, Field

from core import (
    api_router, db, logger,
    EMERGENT_LLM_KEY, ADMIN_EMAILS, STRIPE_API_KEY, USD_TO_BDT, APP_NAME,
    init_storage, put_object, get_object,
    tier_price, calc_discount, _parse_iso,
    TIER_DISCOUNTS, DISCOUNT_TIERS,
    get_current_user, require_user, require_admin,
)

from notifications import notify_kyc_decision
from routes.insights import evaluate_and_apply_auto_upgrade


# ============= Admin: Workshops =============
@api_router.get("/admin/workshops")
async def admin_list_workshops(request: Request, kyc_status: str = ""):
    await require_admin(request)
    flt = {}
    if kyc_status:
        flt["kyc_status"] = kyc_status
    pipeline = [
        {"$match": flt} if flt else {"$match": {}},
        {"$sort": {"created_at": -1}},
        {"$limit": 1000},
        {"$lookup": {
            "from": "users",
            "localField": "user_id",
            "foreignField": "user_id",
            "as": "user",
        }},
        {"$unwind": {"path": "$user", "preserveNullAndEmptyArrays": True}},
        {"$addFields": {
            "email": {"$ifNull": ["$user.email", ""]},
            "owner_name": {"$ifNull": ["$user.name", ""]},
        }},
        {"$project": {"_id": 0, "user": 0}},
    ]
    items = await db.workshops.aggregate(pipeline).to_list(1000)
    return items


@api_router.get("/admin/workshops/{workshop_id}")
async def admin_get_workshop(workshop_id: str, request: Request):
    await require_admin(request)
    w = await db.workshops.find_one({"workshop_id": workshop_id}, {"_id": 0})
    if not w:
        raise HTTPException(404, "Not found")
    u = await db.users.find_one({"user_id": w["user_id"]}, {"_id": 0})
    w["email"] = u["email"] if u else ""
    w["owner_name"] = u["name"] if u else ""
    return w


class KycDecision(BaseModel):
    decision: str  # approved | rejected
    remark: str = ""

@api_router.patch("/admin/workshops/{workshop_id}/kyc")
async def admin_kyc_decision(workshop_id: str, payload: KycDecision, request: Request):
    await require_admin(request)
    if payload.decision not in ["approved", "rejected"]:
        raise HTTPException(400, "Invalid decision")
    await db.workshops.update_one(
        {"workshop_id": workshop_id},
        {"$set": {"kyc_status": payload.decision, "kyc_remark": payload.remark}}
    )
    ws = await db.workshops.find_one({"workshop_id": workshop_id}, {"_id": 0})
    # Fire notification (no-ops if Resend not configured)
    if ws:
        owner = await db.users.find_one({"user_id": ws["user_id"]}, {"_id": 0})
        if owner and owner.get("email"):
            try:
                notify_kyc_decision(ws, owner["email"])
            except Exception as e:
                logger.warning(f"KYC notify failed: {e}")
        # On approval, evaluate Joy Score (sets baseline + may grant initial credit)
        if payload.decision == "approved":
            try:
                await evaluate_and_apply_auto_upgrade(ws["user_id"])
                # refetch to return latest tier/credit
                ws = await db.workshops.find_one({"workshop_id": workshop_id}, {"_id": 0})
            except Exception as e:
                logger.warning(f"KYC auto-upgrade eval failed: {e}")
    return ws


class CreditUpdate(BaseModel):
    credit_limit: float

@api_router.patch("/admin/workshops/{workshop_id}/credit")
async def admin_set_credit(workshop_id: str, payload: CreditUpdate, request: Request):
    await require_admin(request)
    if payload.credit_limit < 0:
        raise HTTPException(400, "Invalid limit")
    await db.workshops.update_one(
        {"workshop_id": workshop_id},
        {"$set": {"credit_limit": payload.credit_limit}}
    )
    return await db.workshops.find_one({"workshop_id": workshop_id}, {"_id": 0})


class TierUpdate(BaseModel):
    pricing_tier: str  # retail | silver | gold | platinum | custom

@api_router.patch("/admin/workshops/{workshop_id}/tier")
async def admin_set_tier(workshop_id: str, payload: TierUpdate, request: Request):
    await require_admin(request)
    if payload.pricing_tier not in ["retail", "silver", "gold", "platinum", "custom"]:
        raise HTTPException(400, "Invalid tier")
    await db.workshops.update_one(
        {"workshop_id": workshop_id},
        {"$set": {"pricing_tier": payload.pricing_tier}}
    )
    return await db.workshops.find_one({"workshop_id": workshop_id}, {"_id": 0})


@api_router.get("/tiers")
async def get_tiers():
    return {"tiers": TIER_DISCOUNTS}



# ============= Reports =============
@api_router.get("/admin/reports/summary")
async def admin_reports_summary(request: Request):
    await require_admin(request)
    sales_pipe = [{"$group": {"_id": None, "revenue": {"$sum": "$total_bdt"},
                              "profit": {"$sum": "$profit_bdt"}, "count": {"$sum": 1}}}]
    s = await db.orders.aggregate(sales_pipe).to_list(1)
    revenue = s[0]["revenue"] if s else 0.0
    profit = s[0].get("profit", 0.0) if s else 0.0
    order_count = s[0]["count"] if s else 0
    top_pipe = [
        {"$unwind": "$items"},
        {"$group": {"_id": "$items.sku", "name": {"$first": "$items.name"},
                    "quantity": {"$sum": "$items.quantity"},
                    "revenue": {"$sum": "$items.line_total"}}},
        {"$sort": {"quantity": -1}}, {"$limit": 20},
    ]
    top_skus = await db.orders.aggregate(top_pipe).to_list(20)
    top_skus = [{"sku": x["_id"], "name": x["name"], "quantity": x["quantity"], "revenue": x["revenue"]}
                for x in top_skus]
    ws_pipe = [
        {"$group": {"_id": "$workshop_id", "company_name": {"$first": "$company_name"},
                    "orders": {"$sum": 1}, "revenue": {"$sum": "$total_bdt"}}},
        {"$sort": {"revenue": -1}}, {"$limit": 20},
    ]
    top_workshops = await db.orders.aggregate(ws_pipe).to_list(20)
    top_workshops = [{"workshop_id": x["_id"], "company_name": x["company_name"],
                      "orders": x["orders"], "revenue": x["revenue"]} for x in top_workshops]
    cat_pipe = [
        {"$unwind": "$items"},
        {"$lookup": {"from": "products", "localField": "items.product_id",
                     "foreignField": "product_id", "as": "prod"}},
        {"$unwind": "$prod"},
        {"$group": {"_id": "$prod.category", "revenue": {"$sum": "$items.line_total"},
                    "quantity": {"$sum": "$items.quantity"}}},
        {"$sort": {"revenue": -1}},
    ]
    by_category = await db.orders.aggregate(cat_pipe).to_list(20)
    by_category = [{"category": x["_id"], "revenue": x["revenue"], "quantity": x["quantity"]}
                   for x in by_category]
    low_stock = await db.products.find({"stock": {"$lt": 10}},
                                       {"_id": 0, "name": 1, "sku": 1, "stock": 1}).to_list(50)
    return {
        "revenue_bdt": revenue, "profit_bdt": profit, "order_count": order_count,
        "gross_margin_pct": round((profit / revenue * 100) if revenue else 0.0, 2),
        "top_skus": top_skus, "top_workshops": top_workshops,
        "by_category": by_category, "low_stock": low_stock,
    }



# ============= Admin: Stats =============
@api_router.get("/admin/stats")
async def admin_stats(request: Request):
    await require_admin(request)
    total_workshops = await db.workshops.count_documents({})
    pending_kyc = await db.workshops.count_documents({"kyc_status": "pending"})
    approved = await db.workshops.count_documents({"kyc_status": "approved"})
    total_orders = await db.orders.count_documents({})
    pending_orders = await db.orders.count_documents({"status": {"$in": ["placed", "confirmed", "packed"]}})
    products_count = await db.products.count_documents({})
    new_inquiries = await db.inquiries.count_documents({"status": "new"})
    new_part_requests = await db.part_requests.count_documents({"status": "new"})

    pipeline = [{"$group": {"_id": None, "total": {"$sum": "$total_bdt"}}}]
    revenue_doc = await db.orders.aggregate(pipeline).to_list(1)
    revenue = revenue_doc[0]["total"] if revenue_doc else 0.0

    return {
        "total_workshops": total_workshops,
        "pending_kyc": pending_kyc,
        "approved_workshops": approved,
        "total_orders": total_orders,
        "pending_orders": pending_orders,
        "products_count": products_count,
        "new_inquiries": new_inquiries,
        "new_part_requests": new_part_requests,
        "total_revenue_bdt": revenue
    }




# ============= Kit Inquiries (public) =============
class KitInquiry(BaseModel):
    name: str
    phone: str
    email: str = ""
    city: str = ""
    car_make_model: str
    kit_sku: str
    message: str = ""


@api_router.post("/inquiries")
async def submit_inquiry(payload: KitInquiry):
    """Public endpoint - retail customers submit kit install inquiries."""
    if not payload.name.strip() or not payload.phone.strip() or not payload.car_make_model.strip():
        raise HTTPException(400, "Name, phone, and car make/model required")
    kit = await db.products.find_one({"sku": payload.kit_sku, "is_kit": True}, {"_id": 0})
    inquiry_id = f"INQ-{datetime.now().strftime('%Y%m%d')}-{uuid.uuid4().hex[:6].upper()}"
    doc = {
        "inquiry_id": inquiry_id,
        "name": payload.name.strip(),
        "phone": payload.phone.strip(),
        "email": payload.email.strip(),
        "city": payload.city.strip(),
        "car_make_model": payload.car_make_model.strip(),
        "kit_sku": payload.kit_sku,
        "kit_name": kit["name"] if kit else payload.kit_sku,
        "message": payload.message.strip(),
        "status": "new",  # new | contacted | scheduled | converted | closed
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    await db.inquiries.insert_one(dict(doc))
    return {"inquiry_id": inquiry_id, "ok": True}


@api_router.get("/admin/inquiries")
async def admin_list_inquiries(request: Request, status: str = ""):
    await require_admin(request)
    flt = {}
    if status:
        flt["status"] = status
    items = await db.inquiries.find(flt, {"_id": 0}).sort("created_at", -1).to_list(500)
    return items


class InquiryStatusUpdate(BaseModel):
    status: str
    admin_note: str = ""


@api_router.patch("/admin/inquiries/{inquiry_id}")
async def admin_update_inquiry(inquiry_id: str, payload: InquiryStatusUpdate, request: Request):
    await require_admin(request)
    valid = ["new", "contacted", "scheduled", "converted", "closed"]
    if payload.status not in valid:
        raise HTTPException(400, f"Invalid status. Use: {valid}")
    await db.inquiries.update_one(
        {"inquiry_id": inquiry_id},
        {"$set": {"status": payload.status, "admin_note": payload.admin_note}},
    )
    return await db.inquiries.find_one({"inquiry_id": inquiry_id}, {"_id": 0})


# ============= Bulk CSV product import =============
@api_router.post("/admin/products/bulk-csv")
async def admin_bulk_csv_import(request: Request, file: UploadFile = File(...)):
    """Admin bulk-import products via CSV.
    Required headers: name,sku,category,price_bdt
    Optional: description,image_url,moq,stock,brand
    """
    await require_admin(request)
    import csv
    import io
    raw = await file.read()
    try:
        text = raw.decode("utf-8-sig")
    except UnicodeDecodeError:
        raise HTTPException(400, "File must be UTF-8 CSV")

    reader = csv.DictReader(io.StringIO(text))
    required = {"name", "sku", "category", "price_bdt"}
    if not reader.fieldnames or not required.issubset(set(h.strip() for h in reader.fieldnames)):
        raise HTTPException(400, f"CSV missing required headers: {sorted(required)}")

    inserted, updated, errors = 0, 0, []
    for i, row in enumerate(reader, start=2):
        try:
            name = row.get("name", "").strip()
            sku = row.get("sku", "").strip()
            category = row.get("category", "").strip()
            price_str = row.get("price_bdt", "").strip()
            if not (name and sku and category and price_str):
                errors.append({"row": i, "error": "missing required field"})
                continue
            doc = {
                "name": name, "sku": sku, "category": category,
                "description": (row.get("description") or "").strip(),
                "image_url": (row.get("image_url") or "").strip(),
                "price_bdt": float(price_str),
                "moq": int(row.get("moq") or 1),
                "stock": int(row.get("stock") or 100),
                "brand": (row.get("brand") or "").strip(),
                "is_kit": False, "kit_tier": "", "kit_features": [], "gallery": [],
            }
            existing = await db.products.find_one({"sku": sku}, {"_id": 0})
            if existing:
                await db.products.update_one({"sku": sku}, {"$set": doc})
                updated += 1
            else:
                doc["product_id"] = f"prd_{uuid.uuid4().hex[:10]}"
                doc["created_at"] = datetime.now(timezone.utc).isoformat()
                await db.products.insert_one(doc)
                inserted += 1
        except Exception as e:
            errors.append({"row": i, "error": str(e)})

    return {"inserted": inserted, "updated": updated, "errors": errors[:20], "total_errors": len(errors)}



# ============= Delivery Persons =============
class DeliveryPerson(BaseModel):
    name: str
    phone: str
    nid_no: str = ""
    vehicle_type: str = ""  # bike | van | pickup | truck
    vehicle_no: str = ""
    coverage_areas: List[str] = []
    status: str = "active"  # active | inactive
    notes: str = ""


@api_router.get("/admin/delivery-persons")
async def admin_list_delivery_persons(request: Request, status: str = ""):
    await require_admin(request)
    flt = {}
    if status:
        flt["status"] = status
    items = await db.delivery_persons.find(flt, {"_id": 0}).sort("created_at", -1).to_list(500)
    # Batch the in-flight order count (avoid N+1 per rider)
    if items:
        ids = [d["delivery_person_id"] for d in items]
        agg = await db.orders.aggregate([
            {"$match": {"delivery_person_id": {"$in": ids}, "status": {"$in": ["packed", "shipped"]}}},
            {"$group": {"_id": "$delivery_person_id", "count": {"$sum": 1}}},
        ]).to_list(500)
        cmap = {x["_id"]: x["count"] for x in agg}
        for d in items:
            d["active_assignments"] = cmap.get(d["delivery_person_id"], 0)
    return items


@api_router.post("/admin/delivery-persons")
async def admin_create_delivery_person(payload: DeliveryPerson, request: Request):
    await require_admin(request)
    if not payload.name.strip() or not payload.phone.strip():
        raise HTTPException(400, "Name and phone required")
    did = f"dp_{uuid.uuid4().hex[:10]}"
    doc = {**payload.model_dump(), "delivery_person_id": did,
           "access_token": uuid.uuid4().hex,
           "created_at": datetime.now(timezone.utc).isoformat()}
    await db.delivery_persons.insert_one(dict(doc))
    doc.pop("_id", None)
    return doc


@api_router.put("/admin/delivery-persons/{delivery_person_id}")
async def admin_update_delivery_person(delivery_person_id: str, payload: DeliveryPerson, request: Request):
    await require_admin(request)
    res = await db.delivery_persons.update_one(
        {"delivery_person_id": delivery_person_id},
        {"$set": payload.model_dump()}
    )
    if res.matched_count == 0:
        raise HTTPException(404, "Delivery person not found")
    return await db.delivery_persons.find_one({"delivery_person_id": delivery_person_id}, {"_id": 0})


@api_router.delete("/admin/delivery-persons/{delivery_person_id}")
async def admin_delete_delivery_person(delivery_person_id: str, request: Request):
    await require_admin(request)
    existing = await db.delivery_persons.find_one(
        {"delivery_person_id": delivery_person_id}, {"_id": 0, "delivery_person_id": 1}
    )
    if not existing:
        raise HTTPException(404, "Delivery person not found")
    inflight = await db.orders.count_documents({
        "delivery_person_id": delivery_person_id,
        "status": {"$in": ["packed", "shipped"]}
    })
    if inflight:
        raise HTTPException(400, f"Cannot delete: {inflight} active assignment(s)")
    await db.delivery_persons.delete_one({"delivery_person_id": delivery_person_id})
    return {"ok": True}


