"""Auto-generated by refactor_split.py — DO NOT edit blindly.

Imports shared singletons (app, api_router, db) and helpers from `core`
to avoid circular dependencies. All `@api_router.*` decorators here
register routes on the same shared router that `server.py` mounts.
"""

import os
import uuid
import json
import requests
from datetime import datetime, timezone, timedelta
from typing import List, Optional

from fastapi import (
    HTTPException, Request, Response, UploadFile, File, Form, Header, Query,
)
from fastapi.responses import Response as FastAPIResponse
from pydantic import BaseModel, Field

from core import (
    api_router, db, logger,
    EMERGENT_LLM_KEY, ADMIN_EMAILS, STRIPE_API_KEY, USD_TO_BDT, APP_NAME,
    init_storage, put_object, get_object,
    tier_price, calc_discount, _parse_iso,
    TIER_DISCOUNTS, DISCOUNT_TIERS,
    get_current_user, require_user, require_admin,
)

from notifications import notify_kyc_decision
from routes.insights import evaluate_and_apply_auto_upgrade
from server_models import Workshop  # noqa: F401  (kept for type hints/back-compat)


# ============= Auth routes =============
@api_router.post("/auth/session")
async def auth_session(request: Request, response: Response):
    body = await request.json()
    session_id = body.get("session_id")
    if not session_id:
        raise HTTPException(status_code=400, detail="session_id required")

    r = requests.get(
        "https://demobackend.emergentagent.com/auth/v1/env/oauth/session-data",
        headers={"X-Session-ID": session_id}, timeout=15
    )
    if r.status_code != 200:
        raise HTTPException(status_code=401, detail="Invalid session")
    data = r.json()
    email = data["email"].lower()
    name = data.get("name", email)
    picture = data.get("picture", "")
    session_token = data["session_token"]

    # Check if first user or in ADMIN_EMAILS - assign admin
    user_count = await db.users.count_documents({})
    role = "admin" if (email in ADMIN_EMAILS or user_count == 0) else "workshop"

    user_doc = await db.users.find_one({"email": email}, {"_id": 0})
    if not user_doc:
        user_id = f"user_{uuid.uuid4().hex[:12]}"
        user_doc = {
            "user_id": user_id,
            "email": email,
            "name": name,
            "picture": picture,
            "role": role,
            "created_at": datetime.now(timezone.utc).isoformat()
        }
        await db.users.insert_one(dict(user_doc))
        # Create workshop record if not admin
        if role == "workshop":
            workshop_id = f"ws_{uuid.uuid4().hex[:12]}"
            await db.workshops.insert_one({
                "workshop_id": workshop_id,
                "user_id": user_id,
                "company_name": "",
                "contact_phone": "",
                "address": "",
                "city": "",
                "trade_license_no": "",
                "kyc_status": "not_submitted",
                "kyc_remark": "",
                "credit_limit": 0.0,
                "credit_used": 0.0,
                "documents": [],
                "created_at": datetime.now(timezone.utc).isoformat()
            })
    else:
        # update name/picture
        await db.users.update_one({"email": email}, {"$set": {"name": name, "picture": picture}})
        user_doc["name"] = name
        user_doc["picture"] = picture

    expires_at = datetime.now(timezone.utc) + timedelta(days=7)
    await db.user_sessions.insert_one({
        "user_id": user_doc["user_id"],
        "session_token": session_token,
        "expires_at": expires_at.isoformat(),
        "created_at": datetime.now(timezone.utc).isoformat()
    })

    response.set_cookie(
        key="session_token", value=session_token,
        httponly=True, secure=True, samesite="none",
        path="/", max_age=7 * 24 * 60 * 60
    )
    # Also return the token in response body so the frontend can use it as a Bearer
    # fallback. This is essential when the API and frontend live on different domains
    # (e.g. custom domain b2bjoymart.com → backend on emergent.host) where the cookie
    # may not be persisted by the browser.
    return {"user": user_doc, "session_token": session_token}


@api_router.get("/auth/me")
async def auth_me(request: Request):
    user = await require_user(request)
    return user


@api_router.post("/auth/logout")
async def auth_logout(request: Request, response: Response):
    token = request.cookies.get("session_token")
    if token:
        await db.user_sessions.delete_one({"session_token": token})
    response.delete_cookie("session_token", path="/", samesite="none", secure=True)
    return {"ok": True}


# ============= Workshop & KYC =============
@api_router.get("/workshop/me")
async def workshop_me(request: Request):
    user = await require_user(request)
    if user.get("role") == "admin":
        return {"is_admin": True, "user": user}
    ws = await db.workshops.find_one({"user_id": user["user_id"]}, {"_id": 0})
    return {"workshop": ws, "user": user}


class WorkshopUpdate(BaseModel):
    company_name: str
    contact_phone: str
    address: str
    city: str
    trade_license_no: str

@api_router.put("/workshop/profile")
async def update_workshop(payload: WorkshopUpdate, request: Request):
    user = await require_user(request)
    await db.workshops.update_one(
        {"user_id": user["user_id"]},
        {"$set": payload.model_dump()}
    )
    ws = await db.workshops.find_one({"user_id": user["user_id"]}, {"_id": 0})
    return ws


@api_router.post("/workshop/kyc/upload")
async def upload_kyc(request: Request, doc_type: str = Form(...), file: UploadFile = File(...)):
    user = await require_user(request)
    ext = file.filename.split(".")[-1].lower() if "." in file.filename else "bin"
    path = f"{APP_NAME}/kyc/{user['user_id']}/{uuid.uuid4().hex}.{ext}"
    data = await file.read()
    if len(data) > 10 * 1024 * 1024:
        raise HTTPException(status_code=400, detail="File too large (max 10MB)")
    result = put_object(path, data, file.content_type or "application/octet-stream")
    doc = {
        "type": doc_type,  # trade_license | nid | owner_photo
        "path": result["path"],
        "filename": file.filename,
        "content_type": file.content_type,
        "uploaded_at": datetime.now(timezone.utc).isoformat()
    }
    await db.workshops.update_one(
        {"user_id": user["user_id"]},
        {"$pull": {"documents": {"type": doc_type}}}
    )
    await db.workshops.update_one(
        {"user_id": user["user_id"]},
        {"$push": {"documents": doc}}
    )
    return doc


@api_router.post("/workshop/kyc/submit")
async def submit_kyc(request: Request):
    user = await require_user(request)
    ws = await db.workshops.find_one({"user_id": user["user_id"]}, {"_id": 0})
    if not ws:
        raise HTTPException(404, "Workshop not found")
    if not ws.get("company_name") or not ws.get("trade_license_no"):
        raise HTTPException(400, "Complete profile first")
    doc_types = {d["type"] for d in ws.get("documents", [])}
    if "trade_license" not in doc_types:
        raise HTTPException(400, "Trade license document required")
    await db.workshops.update_one(
        {"user_id": user["user_id"]},
        {"$set": {"kyc_status": "pending", "kyc_remark": ""}}
    )
    return {"ok": True}


@api_router.get("/files/{path:path}")
async def serve_file(path: str, request: Request):
    user = await require_user(request)
    # Owner or admin can view
    parts = path.split("/")
    if user.get("role") != "admin":
        # path starts with joyautomart/kyc/{user_id}/...
        if len(parts) < 3 or parts[2] != user["user_id"]:
            raise HTTPException(403, "Forbidden")
    data, ctype = get_object(path)
    return Response(content=data, media_type=ctype)

