"""Auto-generated by refactor_split.py — DO NOT edit blindly.

Imports shared singletons (app, api_router, db) and helpers from `core`
to avoid circular dependencies. All `@api_router.*` decorators here
register routes on the same shared router that `server.py` mounts.
"""

import os
import uuid
import json
import requests
from datetime import datetime, timezone, timedelta
from typing import List, Optional

from fastapi import (
    HTTPException, Request, Response, UploadFile, File, Form, Header, Query,
)
from fastapi.responses import Response as FastAPIResponse
from pydantic import BaseModel, Field

from core import (
    api_router, db, logger,
    EMERGENT_LLM_KEY, ADMIN_EMAILS, STRIPE_API_KEY, USD_TO_BDT, APP_NAME,
    init_storage, put_object, get_object,
    tier_price, calc_discount, _parse_iso,
    TIER_DISCOUNTS, DISCOUNT_TIERS,
    get_current_user, require_user, require_admin,
)

from server_models import CartItem  # noqa: F401


# ============= Kits =============
@api_router.get("/kits")
async def list_kits():
    items = await db.products.find({"is_kit": True}, {"_id": 0}).to_list(50)
    # Sort by tier order: entry, mass, special, premium, flagship
    order = {"entry": 1, "mass": 2, "special": 3, "premium": 4, "flagship": 5}
    items.sort(key=lambda x: order.get(x.get("kit_tier", ""), 99))
    return items


@api_router.get("/featured-kit")
async def get_featured_kit():
    """Returns the currently featured kit with workshop pricing."""
    kit = await db.products.find_one({"is_kit": True, "is_featured": True}, {"_id": 0})
    if not kit:
        kit = await db.products.find_one({"is_kit": True, "kit_tier": "flagship"}, {"_id": 0})
        if kit:
            kit["is_featured"] = True
            kit["featured_discount_pct"] = 0.10
            kit["featured_label"] = "Featured Kit · This Month"
    if not kit:
        return None
    discount_pct = float(kit.get("featured_discount_pct", 0.0))
    original = float(kit["price_bdt"])
    workshop_price = round(original * (1 - discount_pct), 2)
    return {
        **kit,
        "workshop_price_bdt": workshop_price,
        "savings_bdt": round(original - workshop_price, 2),
    }


class FeaturedKitUpdate(BaseModel):
    sku: str
    discount_pct: float
    label: str = ""


@api_router.put("/admin/featured-kit")
async def admin_set_featured(payload: FeaturedKitUpdate, request: Request):
    await require_admin(request)
    if payload.discount_pct < 0 or payload.discount_pct > 0.5:
        raise HTTPException(400, "discount_pct must be between 0 and 0.5")
    # Clear previous featured
    await db.products.update_many(
        {"is_kit": True, "is_featured": True},
        {"$set": {"is_featured": False, "featured_discount_pct": 0.0, "featured_label": ""}},
    )
    # Set new
    res = await db.products.update_one(
        {"sku": payload.sku, "is_kit": True},
        {"$set": {
            "is_featured": True,
            "featured_discount_pct": payload.discount_pct,
            "featured_label": payload.label or "Featured Kit · This Month",
        }},
    )
    if res.matched_count == 0:
        raise HTTPException(404, "Kit not found")
    return await db.products.find_one({"sku": payload.sku}, {"_id": 0})




# ============= Service Packs (Bundles) =============
@api_router.get("/service-packs")
async def list_service_packs(request: Request):
    """Return all bundle products (service packs) with tier pricing."""
    items = await db.products.find(
        {"is_bundle": True}, {"_id": 0}
    ).sort("price_bdt", 1).to_list(100)
    user = await get_current_user(request)
    tier = "retail"
    if user and user.get("role") == "workshop":
        ws = await db.workshops.find_one({"user_id": user["user_id"]}, {"_id": 0})
        if ws:
            tier = ws.get("pricing_tier", "silver")
    for p in items:
        p["retail_price_bdt"] = p["price_bdt"]
        p["your_price_bdt"] = tier_price(p["price_bdt"], tier)
        p["your_tier"] = tier
        p.pop("cost_price_bdt", None)
        # Resolve bundle items (read-only, names + skus)
        resolved = []
        for bi in p.get("bundle_items", []):
            child = await db.products.find_one(
                {"product_id": bi["product_id"]}, {"_id": 0}
            )
            if child:
                resolved.append({
                    "product_id": bi["product_id"],
                    "quantity": bi.get("quantity", 1),
                    "name": child["name"],
                    "sku": child["sku"],
                    "image_url": child.get("image_url", ""),
                })
        p["bundle_items_resolved"] = resolved
    return items


# ============= Public Catalog (SEO, no auth) =============
@api_router.get("/public/catalog")
async def public_catalog(category: str = "", q: str = ""):
    """Anonymous catalog snapshot — used for the public /catalog page (SEO).
    Returns retail prices only, no tier discount."""
    flt = {}
    if category:
        flt["category"] = category
    if q:
        rx = {"$regex": q, "$options": "i"}
        flt["$or"] = [{"name": rx}, {"sku": rx}, {"brand": rx}]
    items = await db.products.find(
        flt,
        {"_id": 0, "product_id": 1, "sku": 1, "name": 1, "category": 1, "brand": 1,
         "image_url": 1, "price_bdt": 1, "stock": 1, "is_kit": 1, "is_bundle": 1,
         "car_fits": 1, "description": 1},
    ).sort("category", 1).to_list(500)
    # Normalize category casing on read so 'Brake' vs 'brakes' don't collide downstream
    for p in items:
        if p.get("category"):
            p["category"] = p["category"].strip().title()
    return items


@api_router.get("/public/categories")
async def public_categories():
    cats = await db.products.distinct("category")
    # De-duplicate case-insensitively, return Title-Cased values
    seen = {}
    for c in cats:
        if not c:
            continue
        key = c.strip().lower()
        if key not in seen:
            seen[key] = c.strip().title()
    return sorted(seen.values())


# ============= Saved Bundles (workshop's own service kits) =============
class SavedBundleItem(BaseModel):
    product_id: str
    quantity: int


class SavedBundlePayload(BaseModel):
    name: str
    items: List[SavedBundleItem]


@api_router.post("/workshop/bundles")
async def create_saved_bundle(payload: SavedBundlePayload, request: Request):
    user = await require_user(request)
    ws = await db.workshops.find_one({"user_id": user["user_id"]}, {"_id": 0})
    if not ws:
        raise HTTPException(403, "Workshop only")
    if not payload.name.strip():
        raise HTTPException(400, "Name required")
    if not payload.items:
        raise HTTPException(400, "At least one item required")
    bid = f"bnd_{uuid.uuid4().hex[:10]}"
    doc = {
        "saved_bundle_id": bid,
        "user_id": user["user_id"],
        "workshop_id": ws["workshop_id"],
        "name": payload.name.strip(),
        "items": [it.model_dump() for it in payload.items],
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    await db.saved_bundles.insert_one(dict(doc))
    return {**doc}


@api_router.get("/workshop/bundles")
async def list_saved_bundles(request: Request):
    user = await require_user(request)
    bundles = await db.saved_bundles.find(
        {"user_id": user["user_id"]}, {"_id": 0}
    ).sort("created_at", -1).to_list(100)
    if not bundles:
        return []
    # Resolve product details
    all_ids = list({it["product_id"] for b in bundles for it in b.get("items", [])})
    products = await db.products.find(
        {"product_id": {"$in": all_ids}},
        {"_id": 0, "product_id": 1, "sku": 1, "name": 1, "image_url": 1, "price_bdt": 1, "moq": 1},
    ).to_list(500)
    pmap = {p["product_id"]: p for p in products}
    tier = (await db.workshops.find_one({"user_id": user["user_id"]}, {"_id": 0}) or {}).get("pricing_tier", "silver")
    for b in bundles:
        resolved = []
        total = 0.0
        for it in b.get("items", []):
            p = pmap.get(it["product_id"])
            if not p:
                continue
            yp = tier_price(p["price_bdt"], tier)
            line = yp * it["quantity"]
            total += line
            resolved.append({
                **it,
                "name": p["name"], "sku": p["sku"], "image_url": p.get("image_url", ""),
                "your_price_bdt": yp, "line_total": line,
            })
        b["items_resolved"] = resolved
        b["total_bdt"] = round(total, 2)
    return bundles


@api_router.delete("/workshop/bundles/{bundle_id}")
async def delete_saved_bundle(bundle_id: str, request: Request):
    user = await require_user(request)
    res = await db.saved_bundles.delete_one(
        {"saved_bundle_id": bundle_id, "user_id": user["user_id"]}
    )
    if res.deleted_count == 0:
        raise HTTPException(404, "Not found")
    return {"ok": True}








