"""Auto-generated by refactor_split.py — DO NOT edit blindly.

Imports shared singletons (app, api_router, db) and helpers from `core`
to avoid circular dependencies. All `@api_router.*` decorators here
register routes on the same shared router that `server.py` mounts.
"""

import os
import uuid
import json
import requests
from datetime import datetime, timezone, timedelta
from typing import List, Optional

from fastapi import (
    HTTPException, Request, Response, UploadFile, File, Form, Header, Query,
)
from fastapi.responses import Response as FastAPIResponse
from pydantic import BaseModel, Field

from core import (
    api_router, db, logger,
    EMERGENT_LLM_KEY, ADMIN_EMAILS, STRIPE_API_KEY, USD_TO_BDT, APP_NAME,
    init_storage, put_object, get_object,
    tier_price, calc_discount, _parse_iso,
    TIER_DISCOUNTS, DISCOUNT_TIERS,
    get_current_user, require_user, require_admin,
)

from server_models import OrderCreate, CartItem  # noqa: F401
from notifications import notify_order_placed, notify_order_status, notify_delivery_assigned
from invoice_pdf import render_invoice_pdf
from routes.insights import evaluate_and_apply_auto_upgrade


# ============= Orders =============
@api_router.post("/orders")
async def create_order(payload: OrderCreate, request: Request):
    user = await require_user(request)
    ws = await db.workshops.find_one({"user_id": user["user_id"]}, {"_id": 0})
    if not ws:
        raise HTTPException(403, "Workshop only")
    if ws["kyc_status"] != "approved":
        raise HTTPException(403, "KYC must be approved before placing orders")

    tier = ws.get("pricing_tier", "silver")
    total = 0.0
    cost_total = 0.0
    line_items = []
    for ci in payload.items:
        p = await db.products.find_one({"product_id": ci.product_id}, {"_id": 0})
        if not p:
            raise HTTPException(400, f"Invalid product: {ci.product_id}")
        if ci.quantity < p.get("moq", 1):
            raise HTTPException(400, f"{p['name']} MOQ is {p['moq']}")
        unit_price = tier_price(p["price_bdt"], tier)
        line_total = unit_price * ci.quantity
        cost_total += p.get("cost_price_bdt", 0.0) * ci.quantity
        total += line_total
        line_items.append({
            "product_id": p["product_id"],
            "name": p["name"],
            "sku": p["sku"],
            "image_url": p.get("image_url", ""),
            "price_bdt": unit_price,
            "retail_price_bdt": p["price_bdt"],
            "cost_price_bdt": p.get("cost_price_bdt", 0.0),
            "quantity": ci.quantity,
            "line_total": line_total
        })

    # Apply volume-discount
    discount_pct, discount_amount, tier_label = calc_discount(total)
    grand_total = round(total - discount_amount, 2)

    if payload.payment_method == "credit":
        available = ws["credit_limit"] - ws["credit_used"]
        if grand_total > available:
            raise HTTPException(400, f"Insufficient credit. Available: ৳{available:.2f}")

    order_id = f"ORD-{datetime.now().strftime('%Y%m%d')}-{uuid.uuid4().hex[:6].upper()}"
    now = datetime.now(timezone.utc)
    due_date = (now + timedelta(days=30)).isoformat() if payload.payment_method == "credit" else None

    order = {
        "order_id": order_id,
        "user_id": user["user_id"],
        "workshop_id": ws["workshop_id"],
        "company_name": ws["company_name"],
        "pricing_tier": tier,
        "items": line_items,
        "subtotal_bdt": total,
        "cost_total_bdt": cost_total,
        "discount_pct": discount_pct,
        "discount_amount_bdt": discount_amount,
        "discount_label": tier_label,
        "total_bdt": grand_total,
        "profit_bdt": round(grand_total - cost_total, 2),
        "payment_method": payload.payment_method,
        "payment_status": "unpaid",
        "due_date": due_date,
        "shipping_address": payload.shipping_address,
        "notes": payload.notes,
        "status": "placed",
        "status_history": [{"status": "placed", "at": now.isoformat(), "note": "Order placed"}],
        "created_at": now.isoformat()
    }
    await db.orders.insert_one(dict(order))

    if payload.payment_method == "credit":
        await db.workshops.update_one(
            {"workshop_id": ws["workshop_id"]},
            {"$inc": {"credit_used": grand_total}}
        )

    # Fire order-placed notification
    try:
        notify_order_placed(order, user.get("email", ""))
    except Exception as e:
        logger.warning(f"Order-placed notify failed: {e}")

    # Trigger Joy Score auto-upgrade evaluation (best-effort, never blocks order)
    upgraded = None
    try:
        upgraded = await evaluate_and_apply_auto_upgrade(user["user_id"])
    except Exception as e:
        logger.warning(f"Auto-upgrade eval failed: {e}")

    order.pop("_id", None)
    if upgraded:
        order["tier_upgraded"] = upgraded
    return order


@api_router.get("/orders")
async def list_orders(request: Request, status: str = ""):
    user = await require_user(request)
    flt = {}
    if user.get("role") != "admin":
        flt["user_id"] = user["user_id"]
    if status:
        flt["status"] = status
    orders = await db.orders.find(flt, {"_id": 0}).sort("created_at", -1).to_list(500)
    return orders


@api_router.get("/orders/{order_id}")
async def get_order(order_id: str, request: Request):
    user = await require_user(request)
    order = await db.orders.find_one({"order_id": order_id}, {"_id": 0})
    if not order:
        raise HTTPException(404, "Not found")
    if user.get("role") != "admin" and order["user_id"] != user["user_id"]:
        raise HTTPException(403, "Forbidden")
    return order


class OrderStatusUpdate(BaseModel):
    status: str
    note: str = ""

@api_router.patch("/admin/orders/{order_id}/status")
async def admin_update_order_status(order_id: str, payload: OrderStatusUpdate, request: Request):
    await require_admin(request)
    order = await db.orders.find_one({"order_id": order_id}, {"_id": 0})
    if not order:
        raise HTTPException(404, "Not found")
    valid = ["placed", "confirmed", "packed", "shipped", "delivered", "cancelled"]
    if payload.status not in valid:
        raise HTTPException(400, f"Invalid status. Use: {valid}")
    now = datetime.now(timezone.utc).isoformat()
    await db.orders.update_one(
        {"order_id": order_id},
        {
            "$set": {"status": payload.status},
            "$push": {"status_history": {"status": payload.status, "at": now, "note": payload.note}}
        }
    )
    if payload.status == "cancelled" and order["payment_method"] == "credit" and order.get("payment_status") != "paid":
        await db.workshops.update_one(
            {"workshop_id": order["workshop_id"]},
            {"$inc": {"credit_used": -order["total_bdt"]}}
        )
    fresh = await db.orders.find_one({"order_id": order_id}, {"_id": 0})
    # Fire status-change notification
    try:
        owner = await db.users.find_one({"user_id": fresh["user_id"]}, {"_id": 0})
        if owner and owner.get("email"):
            notify_order_status(fresh, owner["email"], payload.status)
    except Exception as e:
        logger.warning(f"Status notify failed: {e}")
    return fresh


@api_router.patch("/admin/orders/{order_id}/payment")
async def admin_mark_paid(order_id: str, request: Request):
    await require_admin(request)
    order = await db.orders.find_one({"order_id": order_id}, {"_id": 0})
    if not order:
        raise HTTPException(404, "Not found")
    if order.get("payment_status") == "paid":
        return order
    await db.orders.update_one({"order_id": order_id}, {"$set": {"payment_status": "paid"}})
    if order["payment_method"] == "credit":
        await db.workshops.update_one(
            {"workshop_id": order["workshop_id"]},
            {"$inc": {"credit_used": -order["total_bdt"]}}
        )
    return await db.orders.find_one({"order_id": order_id}, {"_id": 0})



# ============= Order: Assign Delivery & Fee =============
class DeliveryAssignment(BaseModel):
    delivery_person_id: str = ""
    delivery_fee_bdt: Optional[float] = None
    expected_delivery_date: str = ""
    note: str = ""


@api_router.patch("/admin/orders/{order_id}/delivery")
async def admin_assign_delivery(order_id: str, payload: DeliveryAssignment, request: Request):
    await require_admin(request)
    order = await db.orders.find_one({"order_id": order_id}, {"_id": 0})
    if not order:
        raise HTTPException(404, "Order not found")
    update = {}
    history_note = ""
    if payload.delivery_person_id:
        dp = await db.delivery_persons.find_one(
            {"delivery_person_id": payload.delivery_person_id}, {"_id": 0}
        )
        if not dp:
            raise HTTPException(400, "Invalid delivery person")
        update["delivery_person_id"] = dp["delivery_person_id"]
        update["delivery_person_name"] = dp["name"]
        update["delivery_person_phone"] = dp["phone"]
        update["delivery_vehicle_no"] = dp.get("vehicle_no", "")
        history_note = f"Delivery assigned to {dp['name']} ({dp['phone']})"
    if payload.delivery_fee_bdt is not None:
        if payload.delivery_fee_bdt < 0:
            raise HTTPException(400, "delivery_fee_bdt must be >= 0")
        # Adjust order total: remove previous fee, add new fee
        prev_fee = order.get("delivery_fee_bdt", 0.0)
        delta = payload.delivery_fee_bdt - prev_fee
        update["delivery_fee_bdt"] = payload.delivery_fee_bdt
        new_total = round(order.get("total_bdt", 0.0) + delta, 2)
        update["total_bdt"] = new_total
        update["profit_bdt"] = round(new_total - order.get("cost_total_bdt", 0.0), 2)
        # Adjust credit usage if credit-paid + still unpaid
        if order.get("payment_method") == "credit" and order.get("payment_status") != "paid" and abs(delta) > 0.001:
            await db.workshops.update_one(
                {"workshop_id": order["workshop_id"]},
                {"$inc": {"credit_used": delta}}
            )
    if payload.expected_delivery_date:
        update["expected_delivery_date"] = payload.expected_delivery_date

    ops = {}
    if update:
        ops["$set"] = update
    if history_note or payload.note:
        ops["$push"] = {"status_history": {
            "status": order.get("status", "placed"),
            "at": datetime.now(timezone.utc).isoformat(),
            "note": payload.note or history_note,
        }}
    if ops:
        await db.orders.update_one({"order_id": order_id}, ops)
    fresh = await db.orders.find_one({"order_id": order_id}, {"_id": 0})
    # Fire delivery-assigned notification (only when rider actually changed)
    if payload.delivery_person_id and fresh and fresh.get("delivery_person_name"):
        try:
            owner = await db.users.find_one({"user_id": fresh["user_id"]}, {"_id": 0})
            if owner and owner.get("email"):
                notify_delivery_assigned(fresh, owner["email"])
        except Exception as e:
            logger.warning(f"Delivery notify failed: {e}")
    return fresh


# ============= Invoice PDF =============
@api_router.get("/orders/{order_id}/invoice.pdf")
async def download_invoice_pdf(order_id: str, request: Request):
    user = await require_user(request)
    order = await db.orders.find_one({"order_id": order_id}, {"_id": 0})
    if not order:
        raise HTTPException(404, "Order not found")
    if user.get("role") != "admin" and order["user_id"] != user["user_id"]:
        raise HTTPException(403, "Forbidden")
    workshop = await db.workshops.find_one(
        {"workshop_id": order["workshop_id"]}, {"_id": 0}
    ) or None
    pdf_bytes = render_invoice_pdf(order, workshop)
    return FastAPIResponse(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="invoice-{order_id}.pdf"',
            "Cache-Control": "no-store",
        },
    )


