"""Auto-generated by refactor_split.py — DO NOT edit blindly.

Imports shared singletons (app, api_router, db) and helpers from `core`
to avoid circular dependencies. All `@api_router.*` decorators here
register routes on the same shared router that `server.py` mounts.
"""

import os
import uuid
import json
import requests
from datetime import datetime, timezone, timedelta
from typing import List, Optional

from fastapi import (
    HTTPException, Request, Response, UploadFile, File, Form, Header, Query,
)
from fastapi.responses import Response as FastAPIResponse
from pydantic import BaseModel, Field

from core import (
    api_router, db, logger,
    EMERGENT_LLM_KEY, ADMIN_EMAILS, STRIPE_API_KEY, USD_TO_BDT, APP_NAME,
    init_storage, put_object, get_object,
    tier_price, calc_discount, _parse_iso,
    TIER_DISCOUNTS, DISCOUNT_TIERS,
    get_current_user, require_user, require_admin,
)

from emergentintegrations.payments.stripe.checkout import (
    StripeCheckout, CheckoutSessionRequest, CheckoutSessionResponse, CheckoutStatusResponse,
)
from server_models import CartItem  # noqa: F401


# ============= Stripe =============
PAYMENT_METHODS = ["credit", "cod", "online"]


class StripeCheckoutCreate(BaseModel):
    items: List[CartItem]
    shipping_address: str
    notes: str = ""
    origin_url: str  # frontend origin (window.location.origin)


@api_router.post("/checkout/create")
async def create_stripe_checkout(payload: StripeCheckoutCreate, request: Request):
    user = await require_user(request)
    ws = await db.workshops.find_one({"user_id": user["user_id"]}, {"_id": 0})
    if not ws:
        raise HTTPException(403, "Workshop only")
    if ws["kyc_status"] != "approved":
        raise HTTPException(403, "KYC must be approved before placing orders")

    # Build line items + total ENTIRELY on backend (never trust frontend amounts)
    total_bdt = 0.0
    line_items = []
    for ci in payload.items:
        p = await db.products.find_one({"product_id": ci.product_id}, {"_id": 0})
        if not p:
            raise HTTPException(400, f"Invalid product: {ci.product_id}")
        if ci.quantity < p.get("moq", 1):
            raise HTTPException(400, f"{p['name']} MOQ is {p['moq']}")
        line_total = p["price_bdt"] * ci.quantity
        total_bdt += line_total
        line_items.append({
            "product_id": p["product_id"], "name": p["name"], "sku": p["sku"],
            "image_url": p.get("image_url", ""), "price_bdt": p["price_bdt"],
            "quantity": ci.quantity, "line_total": line_total,
        })

    # Apply volume discount
    discount_pct, discount_amount, tier_label = calc_discount(total_bdt)
    grand_total = round(total_bdt - discount_amount, 2)

    # Convert BDT -> USD (Stripe doesn't natively support BDT in standard accounts)
    amount_usd = round(grand_total / USD_TO_BDT, 2)
    if amount_usd < 1:
        amount_usd = 1.0  # Stripe minimum

    # Create draft order (status pending_payment) BEFORE redirecting
    order_id = f"ORD-{datetime.now().strftime('%Y%m%d')}-{uuid.uuid4().hex[:6].upper()}"
    now = datetime.now(timezone.utc)
    draft_order = {
        "order_id": order_id,
        "user_id": user["user_id"],
        "workshop_id": ws["workshop_id"],
        "company_name": ws["company_name"],
        "items": line_items,
        "subtotal_bdt": total_bdt,
        "discount_pct": discount_pct,
        "discount_amount_bdt": discount_amount,
        "discount_label": tier_label,
        "total_bdt": grand_total,
        "payment_method": "online",
        "payment_status": "unpaid",
        "due_date": None,
        "shipping_address": payload.shipping_address,
        "notes": payload.notes,
        "status": "pending_payment",
        "status_history": [{"status": "pending_payment", "at": now.isoformat(), "note": "Awaiting online payment"}],
        "created_at": now.isoformat(),
    }
    await db.orders.insert_one(dict(draft_order))

    success_url = f"{payload.origin_url}/payment/return?session_id={{CHECKOUT_SESSION_ID}}"
    cancel_url = f"{payload.origin_url}/cart"
    host_url = str(request.base_url)
    webhook_url = f"{host_url}api/webhook/stripe"
    stripe_checkout = StripeCheckout(api_key=STRIPE_API_KEY, webhook_url=webhook_url)
    sess_req = CheckoutSessionRequest(
        amount=float(amount_usd), currency="usd",
        success_url=success_url, cancel_url=cancel_url,
        metadata={"order_id": order_id, "user_id": user["user_id"], "workshop_id": ws["workshop_id"]},
    )
    try:
        session: CheckoutSessionResponse = await stripe_checkout.create_checkout_session(sess_req)
    except Exception as e:
        # Roll back orphaned draft order so /api/orders doesn't show ghost entries
        await db.orders.delete_one({"order_id": order_id})
        logger.error(f"Stripe session creation failed for order {order_id}: {e}")
        raise HTTPException(status_code=502, detail="Payment gateway unavailable. Please try again.")

    # Record transaction
    await db.payment_transactions.insert_one({
        "transaction_id": f"txn_{uuid.uuid4().hex[:12]}",
        "session_id": session.session_id,
        "order_id": order_id,
        "user_id": user["user_id"],
        "amount_bdt": grand_total,
        "amount_usd": amount_usd,
        "currency": "usd",
        "metadata": {"order_id": order_id, "user_id": user["user_id"]},
        "payment_status": "initiated",
        "status": "pending",
        "created_at": now.isoformat(),
    })

    return {"url": session.url, "session_id": session.session_id, "order_id": order_id}


# ============= Quote / Discount =============
class QuoteRequest(BaseModel):
    items: List[CartItem]


@api_router.post("/quote")
async def quote_cart(payload: QuoteRequest, request: Request):
    """Live cart preview with applied volume discount tier."""
    await require_user(request)
    subtotal = 0.0
    for ci in payload.items:
        p = await db.products.find_one({"product_id": ci.product_id}, {"_id": 0})
        if not p:
            continue
        subtotal += p["price_bdt"] * ci.quantity
    discount_pct, discount_amount, tier_label = calc_discount(subtotal)
    grand_total = round(subtotal - discount_amount, 2)
    return {
        "subtotal_bdt": subtotal,
        "discount_pct": discount_pct,
        "discount_amount_bdt": discount_amount,
        "discount_label": tier_label,
        "total_bdt": grand_total,
        "tiers": [
            {"threshold_bdt": t, "discount_pct": p, "label": f"৳{int(t):,}+"} for t, p in DISCOUNT_TIERS
        ],
    }





@api_router.get("/checkout/status/{session_id}")
async def stripe_checkout_status(session_id: str, request: Request):
    user = await require_user(request)
    txn = await db.payment_transactions.find_one({"session_id": session_id}, {"_id": 0})
    if not txn:
        raise HTTPException(404, "Transaction not found")
    if txn["user_id"] != user["user_id"]:
        raise HTTPException(403, "Forbidden")

    # If already finalized, return cached
    if txn["payment_status"] == "paid":
        return {"payment_status": "paid", "status": "complete", "order_id": txn["order_id"]}

    host_url = str(request.base_url)
    webhook_url = f"{host_url}api/webhook/stripe"
    stripe_checkout = StripeCheckout(api_key=STRIPE_API_KEY, webhook_url=webhook_url)
    status: CheckoutStatusResponse = await stripe_checkout.get_checkout_status(session_id)

    new_payment_status = status.payment_status
    new_status = status.status
    update = {"payment_status": new_payment_status, "status": new_status}
    await db.payment_transactions.update_one({"session_id": session_id}, {"$set": update})

    # If paid and order not yet finalized, finalize once
    if new_payment_status == "paid" and txn["payment_status"] != "paid":
        order = await db.orders.find_one({"order_id": txn["order_id"]}, {"_id": 0})
        if order and order.get("status") == "pending_payment":
            now = datetime.now(timezone.utc).isoformat()
            await db.orders.update_one(
                {"order_id": txn["order_id"]},
                {
                    "$set": {"status": "placed", "payment_status": "paid"},
                    "$push": {"status_history": {"status": "placed", "at": now, "note": "Online payment received"}},
                },
            )

    return {"payment_status": new_payment_status, "status": new_status, "order_id": txn["order_id"]}


@api_router.post("/webhook/stripe")
async def stripe_webhook(request: Request):
    body = await request.body()
    signature = request.headers.get("Stripe-Signature")
    host_url = str(request.base_url)
    webhook_url = f"{host_url}api/webhook/stripe"
    stripe_checkout = StripeCheckout(api_key=STRIPE_API_KEY, webhook_url=webhook_url)
    try:
        event = await stripe_checkout.handle_webhook(body, signature)
    except Exception as e:
        logger.error(f"Webhook error: {e}")
        raise HTTPException(400, "Invalid webhook")

    if event.payment_status == "paid":
        txn = await db.payment_transactions.find_one({"session_id": event.session_id}, {"_id": 0})
        if txn and txn["payment_status"] != "paid":
            await db.payment_transactions.update_one(
                {"session_id": event.session_id},
                {"$set": {"payment_status": "paid", "status": "complete"}},
            )
            order = await db.orders.find_one({"order_id": txn["order_id"]}, {"_id": 0})
            if order and order.get("status") == "pending_payment":
                now = datetime.now(timezone.utc).isoformat()
                await db.orders.update_one(
                    {"order_id": txn["order_id"]},
                    {
                        "$set": {"status": "placed", "payment_status": "paid"},
                        "$push": {"status_history": {"status": "placed", "at": now, "note": "Online payment received (webhook)"}},
                    },
                )
    return {"ok": True}


