"""Auto-generated by refactor_split.py — DO NOT edit blindly.

Imports shared singletons (app, api_router, db) and helpers from `core`
to avoid circular dependencies. All `@api_router.*` decorators here
register routes on the same shared router that `server.py` mounts.
"""

import os
import uuid
import json
import requests
from datetime import datetime, timezone, timedelta
from typing import List, Optional

from fastapi import (
    HTTPException, Request, Response, UploadFile, File, Form, Header, Query,
)
from fastapi.responses import Response as FastAPIResponse
from pydantic import BaseModel, Field

from core import (
    api_router, db, logger,
    EMERGENT_LLM_KEY, ADMIN_EMAILS, STRIPE_API_KEY, USD_TO_BDT, APP_NAME,
    init_storage, put_object, get_object,
    tier_price, calc_discount, _parse_iso,
    TIER_DISCOUNTS, DISCOUNT_TIERS,
    get_current_user, require_user, require_admin,
)

from server_models import Product, CartItem  # noqa: F401



# ============= Vehicle filter options (cascade tree) =============
@api_router.get("/vehicles/options")
async def vehicle_options():
    """Return a cascade tree of {brand → model → years[]} aggregated from all
    products' car_fits arrays. Used by the catalog page's cascading vehicle
    filter (Make → Model → Year). Excludes universal-fit products."""
    products = await db.products.find(
        {"car_fits": {"$exists": True, "$ne": []}},
        {"_id": 0, "car_fits": 1},
    ).to_list(1000)

    tree: dict = {}
    for p in products:
        for fit in p.get("car_fits", []):
            if not isinstance(fit, dict):
                continue
            brand = (fit.get("brand") or "").strip()
            model = (fit.get("model") or "").strip()
            yf = int(fit.get("year_from") or 0)
            yt = int(fit.get("year_to") or 0)
            if not brand or not model:
                continue
            tree.setdefault(brand, {}).setdefault(model, set())
            if yf and yt and yt >= yf:
                for y in range(yf, yt + 1):
                    tree[brand][model].add(y)

    # Serialize to sorted JSON-friendly structure
    out = {
        "brands": sorted(tree.keys()),
        "by_brand": {
            brand: {
                "models": sorted(models.keys()),
                "by_model": {
                    model: sorted(years) for model, years in models.items()
                },
            }
            for brand, models in tree.items()
        },
    }
    return out


# ============= Products =============
@api_router.get("/products")
async def list_products(request: Request, q: str = "", category: str = "",
                        car_brand: str = "", car_model: str = "", car_year: int = 0):
    flt = {}
    if q:
        flt["$or"] = [
            {"name": {"$regex": q, "$options": "i"}},
            {"sku": {"$regex": q, "$options": "i"}},
            {"brand": {"$regex": q, "$options": "i"}},
        ]
    if category:
        flt["category"] = category
    if car_brand:
        flt["car_fits.brand"] = {"$regex": f"^{car_brand}$", "$options": "i"}
    if car_model:
        flt["car_fits.model"] = {"$regex": car_model, "$options": "i"}
    items = await db.products.find(flt, {"_id": 0}).to_list(500)
    if car_year:
        items = [p for p in items if any(
            (f.get("year_from", 0) <= car_year <= f.get("year_to", 9999))
            for f in p.get("car_fits", [])
        ) or not p.get("car_fits")]

    # Apply workshop tier pricing if authenticated as workshop
    user = await get_current_user(request)
    tier = "retail"
    if user and user.get("role") == "workshop":
        ws = await db.workshops.find_one({"user_id": user["user_id"]}, {"_id": 0})
        if ws:
            tier = ws.get("pricing_tier", "silver")

    for p in items:
        p["retail_price_bdt"] = p["price_bdt"]
        p["your_price_bdt"] = tier_price(p["price_bdt"], tier)
        p["your_tier"] = tier
        p.pop("cost_price_bdt", None)  # Hide cost price from non-admins
    return items


@api_router.get("/products/{product_id}")
async def get_product(product_id: str, request: Request):
    p = await db.products.find_one({"product_id": product_id}, {"_id": 0})
    if not p:
        raise HTTPException(404, "Not found")
    user = await get_current_user(request)
    tier = "retail"
    if user and user.get("role") == "workshop":
        ws = await db.workshops.find_one({"user_id": user["user_id"]}, {"_id": 0})
        if ws:
            tier = ws.get("pricing_tier", "silver")
    p["retail_price_bdt"] = p["price_bdt"]
    p["your_price_bdt"] = tier_price(p["price_bdt"], tier)
    p["your_tier"] = tier
    if not (user and user.get("role") == "admin"):
        p.pop("cost_price_bdt", None)
    # Resolve bundle items
    if p.get("is_bundle") and p.get("bundle_items"):
        ids = [bi["product_id"] for bi in p["bundle_items"]]
        children = await db.products.find(
            {"product_id": {"$in": ids}},
            {"_id": 0, "product_id": 1, "name": 1, "sku": 1, "image_url": 1},
        ).to_list(100)
        cmap = {c["product_id"]: c for c in children}
        resolved = []
        for bi in p["bundle_items"]:
            child = cmap.get(bi["product_id"])
            if child:
                resolved.append({**bi, "name": child["name"], "sku": child["sku"], "image_url": child.get("image_url", "")})
        p["bundle_items_resolved"] = resolved
    return p


class ProductCreate(BaseModel):
    name: str
    sku: str
    category: str
    description: str = ""
    image_url: str = ""
    price_bdt: float
    cost_price_bdt: float = 0.0
    moq: int = 1
    stock: int = 100
    brand: str = ""
    is_kit: bool = False
    kit_tier: str = ""
    kit_features: List[str] = []
    gallery: List[str] = []
    car_fits: List[dict] = []
    is_bundle: bool = False
    bundle_items: List[dict] = []

@api_router.post("/admin/products")
async def admin_create_product(payload: ProductCreate, request: Request):
    await require_admin(request)
    pid = f"prd_{uuid.uuid4().hex[:10]}"
    doc = {**payload.model_dump(), "product_id": pid, "created_at": datetime.now(timezone.utc).isoformat()}
    await db.products.insert_one(dict(doc))
    doc.pop("_id", None)
    return doc


@api_router.put("/admin/products/{product_id}")
async def admin_update_product(product_id: str, payload: ProductCreate, request: Request):
    await require_admin(request)
    await db.products.update_one({"product_id": product_id}, {"$set": payload.model_dump()})
    return await db.products.find_one({"product_id": product_id}, {"_id": 0})


@api_router.delete("/admin/products/{product_id}")
async def admin_delete_product(product_id: str, request: Request):
    await require_admin(request)
    await db.products.delete_one({"product_id": product_id})
    return {"ok": True}


