"""Auto-generated by refactor_split.py — DO NOT edit blindly.

Imports shared singletons (app, api_router, db) and helpers from `core`
to avoid circular dependencies. All `@api_router.*` decorators here
register routes on the same shared router that `server.py` mounts.
"""

import os
import uuid
import json
import requests
from datetime import datetime, timezone, timedelta
from typing import List, Optional

from fastapi import (
    HTTPException, Request, Response, UploadFile, File, Form, Header, Query,
)
from fastapi.responses import Response as FastAPIResponse
from pydantic import BaseModel, Field

from core import (
    api_router, db, logger,
    EMERGENT_LLM_KEY, ADMIN_EMAILS, STRIPE_API_KEY, USD_TO_BDT, APP_NAME,
    init_storage, put_object, get_object,
    tier_price, calc_discount, _parse_iso,
    TIER_DISCOUNTS, DISCOUNT_TIERS,
    get_current_user, require_user, require_admin,
)

from notifications import notify_order_status  # reused for return notifications


# ============= Returns / RMA =============
RETURN_WINDOW_DAYS = 7


class ReturnItem(BaseModel):
    product_id: str
    quantity: int
    reason: str = ""


class ReturnCreate(BaseModel):
    order_id: str
    items: List[ReturnItem]
    reason: str = ""


# _parse_iso lives in core.py


@api_router.post("/returns")
async def create_return(payload: ReturnCreate, request: Request):
    user = await require_user(request)
    ws = await db.workshops.find_one({"user_id": user["user_id"]}, {"_id": 0})
    if not ws:
        raise HTTPException(403, "Workshop only")
    order = await db.orders.find_one({"order_id": payload.order_id}, {"_id": 0})
    if not order:
        raise HTTPException(404, "Order not found")
    if order["user_id"] != user["user_id"]:
        raise HTTPException(403, "Not your order")
    if order.get("status") != "delivered":
        raise HTTPException(400, "Returns only allowed after delivery")
    # Find delivered timestamp
    delivered_at = None
    for h in order.get("status_history", []):
        if h.get("status") == "delivered":
            delivered_at = _parse_iso(h.get("at"))
    if not delivered_at:
        delivered_at = _parse_iso(order.get("created_at"))
    if delivered_at and (datetime.now(timezone.utc) - delivered_at).days > RETURN_WINDOW_DAYS:
        raise HTTPException(400, f"Return window ({RETURN_WINDOW_DAYS} days) has passed")
    if not payload.items:
        raise HTTPException(400, "At least one item required")

    # Validate items vs order; cap qty by order qty
    order_lookup = {it["product_id"]: it for it in order.get("items", [])}
    order_subtotal = float(order.get("subtotal_bdt") or 0.0) or 1.0  # avoid div-by-zero
    order_total = float(order.get("total_bdt") or 0.0)
    # Effective discount factor: ratio of what customer actually paid (post discount, post fee)
    # vs the gross subtotal. Applied per-line so refund matches what they paid.
    effective_factor = (order_total / order_subtotal) if order_subtotal > 0 else 1.0
    # Cap factor at 1.0 (don't refund more than gross when delivery fee inflates total)
    if effective_factor > 1.0:
        effective_factor = 1.0
    enriched = []
    refund_total = 0.0
    for ri in payload.items:
        if ri.product_id not in order_lookup:
            raise HTTPException(400, f"Item {ri.product_id} not in order")
        if ri.quantity <= 0:
            raise HTTPException(400, "Quantity must be > 0")
        order_item = order_lookup[ri.product_id]
        if ri.quantity > order_item.get("quantity", 0):
            raise HTTPException(400, f"Quantity exceeds ordered for {order_item.get('name')}")
        gross_line = order_item.get("price_bdt", 0.0) * ri.quantity
        line_refund = round(gross_line * effective_factor, 2)
        refund_total += line_refund
        enriched.append({
            "product_id": ri.product_id,
            "sku": order_item.get("sku", ""),
            "name": order_item.get("name", ""),
            "image_url": order_item.get("image_url", ""),
            "quantity": ri.quantity,
            "price_bdt": order_item.get("price_bdt", 0.0),
            "line_refund_bdt": line_refund,
            "reason": ri.reason or payload.reason or "",
        })

    return_id = f"RMA-{datetime.now().strftime('%Y%m%d')}-{uuid.uuid4().hex[:6].upper()}"
    now = datetime.now(timezone.utc).isoformat()
    doc = {
        "return_id": return_id,
        "order_id": order["order_id"],
        "user_id": user["user_id"],
        "workshop_id": ws["workshop_id"],
        "company_name": ws.get("company_name", ""),
        "items": enriched,
        "reason": payload.reason or "",
        "refund_total_bdt": round(refund_total, 2),
        "refund_method": "",  # set on approval
        "status": "requested",  # requested | approved | rejected | completed
        "admin_note": "",
        "status_history": [{"status": "requested", "at": now, "note": "Return requested"}],
        "created_at": now,
    }
    await db.returns.insert_one(dict(doc))
    return {"return_id": return_id, "ok": True}


@api_router.get("/returns")
async def list_my_returns(request: Request, status: str = ""):
    user = await require_user(request)
    flt = {}
    if user.get("role") != "admin":
        flt["user_id"] = user["user_id"]
    if status:
        flt["status"] = status
    items = await db.returns.find(flt, {"_id": 0}).sort("created_at", -1).to_list(500)
    return items


@api_router.get("/returns/{return_id}")
async def get_return(return_id: str, request: Request):
    user = await require_user(request)
    r = await db.returns.find_one({"return_id": return_id}, {"_id": 0})
    if not r:
        raise HTTPException(404, "Not found")
    if user.get("role") != "admin" and r["user_id"] != user["user_id"]:
        raise HTTPException(403, "Forbidden")
    return r


class ReturnDecision(BaseModel):
    decision: str  # approved | rejected | completed
    refund_method: str = ""  # credit-back | reship | cash
    admin_note: str = ""


@api_router.patch("/admin/returns/{return_id}")
async def admin_decide_return(return_id: str, payload: ReturnDecision, request: Request):
    await require_admin(request)
    r = await db.returns.find_one({"return_id": return_id}, {"_id": 0})
    if not r:
        raise HTTPException(404, "Return not found")
    if payload.decision not in ["approved", "rejected", "completed"]:
        raise HTTPException(400, "Invalid decision")
    if r["status"] in ["rejected", "completed"]:
        raise HTTPException(400, f"Return already {r['status']}")

    update = {
        "status": payload.decision,
        "admin_note": payload.admin_note or r.get("admin_note", ""),
    }
    if payload.refund_method:
        if payload.refund_method not in ["credit-back", "reship", "cash"]:
            raise HTTPException(400, "Invalid refund_method")
        update["refund_method"] = payload.refund_method

    # On approval: restock, refund credit if applicable
    if payload.decision == "approved" and r["status"] == "requested":
        for it in r["items"]:
            await db.products.update_one(
                {"product_id": it["product_id"]},
                {"$inc": {"stock": int(it["quantity"])}}
            )
        # If refund_method credit-back: decrement workshop's credit_used
        order = await db.orders.find_one({"order_id": r["order_id"]}, {"_id": 0})
        if (
            payload.refund_method == "credit-back"
            and order
            and order.get("payment_method") == "credit"
        ):
            await db.workshops.update_one(
                {"workshop_id": r["workshop_id"]},
                {"$inc": {"credit_used": -r["refund_total_bdt"]}}
            )

    now = datetime.now(timezone.utc).isoformat()
    history = {"status": payload.decision, "at": now, "note": payload.admin_note or ""}
    await db.returns.update_one(
        {"return_id": return_id},
        {"$set": update, "$push": {"status_history": history}}
    )
    return await db.returns.find_one({"return_id": return_id}, {"_id": 0})


@api_router.get("/admin/returns")
async def admin_list_returns(request: Request, status: str = ""):
    await require_admin(request)
    flt = {}
    if status:
        flt["status"] = status
    items = await db.returns.find(flt, {"_id": 0}).sort("created_at", -1).to_list(500)
    return items


