"""Auto-generated by refactor_split.py — DO NOT edit blindly.

Imports shared singletons (app, api_router, db) and helpers from `core`
to avoid circular dependencies. All `@api_router.*` decorators here
register routes on the same shared router that `server.py` mounts.
"""

import os
import uuid
import json
import requests
from datetime import datetime, timezone, timedelta
from typing import List, Optional

from fastapi import (
    HTTPException, Request, Response, UploadFile, File, Form, Header, Query,
)
from fastapi.responses import Response as FastAPIResponse
from pydantic import BaseModel, Field

from core import (
    api_router, db, logger,
    EMERGENT_LLM_KEY, ADMIN_EMAILS, STRIPE_API_KEY, USD_TO_BDT, APP_NAME,
    init_storage, put_object, get_object,
    tier_price, calc_discount, _parse_iso,
    TIER_DISCOUNTS, DISCOUNT_TIERS,
    get_current_user, require_user, require_admin,
)


# ============= Part Requests (Sourcing) =============
class PartRequestCreate(BaseModel):
    car_brand: str
    car_model: str
    car_year: int = 0
    vin_chassis: str = ""
    part_name: str
    part_number: str = ""
    quantity: int = 1
    urgency: str = "normal"
    budget_bdt: float = 0.0
    notes: str = ""
    photo_urls: List[str] = []


@api_router.post("/part-requests")
async def create_part_request(payload: PartRequestCreate, request: Request):
    user = await require_user(request)
    ws = await db.workshops.find_one({"user_id": user["user_id"]}, {"_id": 0})
    if not ws:
        raise HTTPException(403, "Workshop only")
    if not payload.car_brand.strip() or not payload.part_name.strip():
        raise HTTPException(400, "Car brand and part name required")
    req_id = f"PRT-{datetime.now().strftime('%Y%m%d')}-{uuid.uuid4().hex[:6].upper()}"
    now = datetime.now(timezone.utc).isoformat()
    doc = {
        "request_id": req_id, "user_id": user["user_id"], "workshop_id": ws["workshop_id"],
        "company_name": ws["company_name"],
        "car_brand": payload.car_brand.strip(), "car_model": payload.car_model.strip(),
        "car_year": payload.car_year, "vin_chassis": payload.vin_chassis.strip(),
        "part_name": payload.part_name.strip(), "part_number": payload.part_number.strip(),
        "quantity": payload.quantity, "urgency": payload.urgency, "budget_bdt": payload.budget_bdt,
        "notes": payload.notes.strip(), "photo_urls": payload.photo_urls,
        "status": "new",
        "status_history": [{"status": "new", "at": now, "note": "Request submitted"}],
        "quote_bdt": 0.0, "quote_lead_time_days": 0,
        "supplier_note": "", "admin_note": "", "order_id": "",
        "created_at": now,
    }
    await db.part_requests.insert_one(dict(doc))
    return {"request_id": req_id, "ok": True}


@api_router.get("/part-requests")
async def list_my_part_requests(request: Request, status: str = ""):
    user = await require_user(request)
    flt = {}
    if user.get("role") == "workshop":
        flt["user_id"] = user["user_id"]
    if status:
        flt["status"] = status
    items = await db.part_requests.find(flt, {"_id": 0}).sort("created_at", -1).to_list(500)
    return items


@api_router.get("/part-requests/{request_id}")
async def get_part_request(request_id: str, request: Request):
    user = await require_user(request)
    r = await db.part_requests.find_one({"request_id": request_id}, {"_id": 0})
    if not r:
        raise HTTPException(404, "Not found")
    if user.get("role") != "admin" and r["user_id"] != user["user_id"]:
        raise HTTPException(403, "Forbidden")
    return r


@api_router.get("/admin/part-requests")
async def admin_list_part_requests(request: Request, status: str = ""):
    await require_admin(request)
    flt = {}
    if status:
        flt["status"] = status
    items = await db.part_requests.find(flt, {"_id": 0}).sort("created_at", -1).to_list(500)
    return items


class PartRequestUpdate(BaseModel):
    status: str = ""
    quote_bdt: float = 0.0
    quote_lead_time_days: int = 0
    supplier_note: str = ""
    admin_note: str = ""
    note: str = ""


@api_router.patch("/admin/part-requests/{request_id}")
async def admin_update_part_request(request_id: str, payload: PartRequestUpdate, request: Request):
    await require_admin(request)
    valid = ["new", "checking", "quoted", "confirmed", "ordered", "delivered", "cancelled"]
    update = {}
    if payload.quote_bdt > 0:
        update["quote_bdt"] = payload.quote_bdt
    if payload.quote_lead_time_days > 0:
        update["quote_lead_time_days"] = payload.quote_lead_time_days
    if payload.supplier_note:
        update["supplier_note"] = payload.supplier_note
    if payload.admin_note:
        update["admin_note"] = payload.admin_note
    push = {}
    if payload.status:
        if payload.status not in valid:
            raise HTTPException(400, f"Invalid status. Use: {valid}")
        update["status"] = payload.status
        push["status_history"] = {"status": payload.status,
                                  "at": datetime.now(timezone.utc).isoformat(), "note": payload.note}
    ops = {}
    if update:
        ops["$set"] = update
    if push:
        ops["$push"] = push
    if ops:
        await db.part_requests.update_one({"request_id": request_id}, ops)
    return await db.part_requests.find_one({"request_id": request_id}, {"_id": 0})


# ============= Suppliers =============
class SupplierCreate(BaseModel):
    name: str
    country: str = ""
    contact_person: str = ""
    phone_whatsapp: str = ""
    email: str = ""
    categories: List[str] = []
    moq: str = ""
    lead_time_days: int = 0
    payment_terms: str = ""
    rating: int = 0
    notes: str = ""


@api_router.get("/admin/suppliers")
async def admin_list_suppliers(request: Request):
    await require_admin(request)
    items = await db.suppliers.find({}, {"_id": 0}).sort("created_at", -1).to_list(500)
    return items


@api_router.post("/admin/suppliers")
async def admin_create_supplier(payload: SupplierCreate, request: Request):
    await require_admin(request)
    if not payload.name.strip():
        raise HTTPException(400, "Name required")
    sid = f"sup_{uuid.uuid4().hex[:10]}"
    doc = {**payload.model_dump(), "supplier_id": sid, "created_at": datetime.now(timezone.utc).isoformat()}
    await db.suppliers.insert_one(dict(doc))
    doc.pop("_id", None)
    return doc


@api_router.put("/admin/suppliers/{supplier_id}")
async def admin_update_supplier(supplier_id: str, payload: SupplierCreate, request: Request):
    await require_admin(request)
    await db.suppliers.update_one({"supplier_id": supplier_id}, {"$set": payload.model_dump()})
    return await db.suppliers.find_one({"supplier_id": supplier_id}, {"_id": 0})


@api_router.delete("/admin/suppliers/{supplier_id}")
async def admin_delete_supplier(supplier_id: str, request: Request):
    await require_admin(request)
    await db.suppliers.delete_one({"supplier_id": supplier_id})
    return {"ok": True}


